--DROP TABLES
DROP TABLE STUDENT;

--CREATE TABLES
CREATE TABLE STUDENT
(
S_ID INT,
S_NAME VARCHAR2(255),
S_AGE INT,
PRIMARY KEY(S_ID)
);

--CREATE SEQUENCES
CREATE SEQUENCE S_SEQ
  START WITH 1
  INCREMENT BY 1;
  
  --CREATE TRIGGERS
CREATE OR REPLACE TRIGGER S_SEQ_TRIGGER
BEFORE INSERT ON STUDENT
FOR EACH ROW --required if you want to see/manipulate the row's data
BEGIN
      SELECT S_SEQ.nextval INTO :new.S_ID FROM DUAL; 
      --DUAL is a dummy table, typically used when you don't require a table 
      --but you still need the syntax of a sql statement to be correct
END;

--INSERT INTO TABLES

INSERT INTO STUDENT(S_NAME, S_AGE) VALUES ('Nick', 39);
INSERT INTO STUDENT(S_NAME, S_AGE) VALUES ('Richard', 25);
INSERT INTO STUDENT(S_NAME, S_AGE) VALUES ('Sean', 19);
INSERT INTO STUDENT(S_NAME, S_AGE) VALUES ('Emily', 22);
INSERT INTO STUDENT(S_NAME, S_AGE) VALUES ('Sam', 55);
INSERT INTO STUDENT(S_NAME, S_AGE) VALUES ('Joe', 29);
INSERT INTO STUDENT(S_NAME, S_AGE) VALUES ('Steven', 44);
INSERT INTO STUDENT(S_NAME, S_AGE) VALUES ('Yuvi', 33);
INSERT INTO STUDENT(S_NAME, S_AGE) VALUES ('Ankid', 36);
INSERT INTO STUDENT(S_NAME, S_AGE) VALUES ('Taylor', 29);