package com.mory;

public class Account {
	private int accountNumber;
	private double balance;
	private static int baseAccountNumber = 499;
	private String accountype;
	private boolean IsApproved;

	// Autogenerate account number when an account is created with an itinial
	// deposit
	public Account(String accountType, double balance) {
		this.balance = balance;
		baseAccountNumber++;
		this.accountNumber = baseAccountNumber;
		this.accountype = accountType.toUpperCase();

	}

	// Can withdraw only when balance is greater than amount you want to
	// withdraw
	public boolean withdraw(double amount) {
		if (balance > amount) {
			balance = -amount;
			return true;
		}
		return false;
	}
	// can deposit only when the amount being deposited is positive

	public boolean deposit(double amount) {
		if (!isApproved()) {
			if (amount > 0) {
				balance += amount;
				return true;
			}
		}
		return IsApproved;
	}

	// Return the autogenerated account number
	public int getAccountNumber() {
		return accountNumber;
	}

	// return the account balance
	public double getBalance() {
		return balance;
	}

	// set the account balance
	public void setBalance(double balance) {
		if(!isApproved())
			this.balance = balance;
	}

	public void setAccountype(String accountype) {
		this.accountype = accountype;
	}

	public boolean isApproved() {
		return IsApproved;
	}

	

}