MINNCOMM BANKING APPLICATION READ ME FILE

OPENS TO THE USER INTERFACE WHICH DIPLAYS A MENU THAT 
ALLOWS 4 OPTIONS: 

1. SIGN UP FOR SERVICE
2. CUSTOMER LOGIN
3. EMPLOYEE LOGIN
4. EXIT

A CUSTOMER NEEDS A LOGIN TO GAIN ACCESS TO THE APPLICATION
IF THEY DO NOT HAVE ONE THEY CAN SELECT OPTION 1 TO SIGN
UP FOR THE SERVCE.

THE CURRENT APPLICATION ASKS THE USER WHAT TYPE OF ACCOUNT
THEY WOULD LIKE TO OPEN UP, BUT EMPLOYEES WOULD 
BE SET UP BY AN ADMIN INDIVIDUAL.  CURRENTLY THE APPLICATION
SETS THE LEVEL FOR A CUSTOMER AND EMPLOYEE TO A VALUE WHICH
DETERMINES WHAT MENU THEY CAN SEE.

FROM HERE IT TAKES YOU TO ENTER IN YOUR PERSONAL INFORMATION
FOR THE ACCOUNT CREATION AND USE CAPABILITY.  AFTER CREATION
THE APPLICATION DISPLAYS THE LOGIN SCREEN.

THE USER ENTERS IN A CORRECT USERNAME AND PASSWORD TO GAIN
ENTRY INTO THE SYSTEM WHERE THE ACCOUNT MENU IS DISPLAYED 
AND HERE IS MAIN MENU FROM WITHIN THE APPLICATION. 
CAPABILITIES:

1. OPEN AN ACCOUNT - CHECKING AND SAVINGS
2. VIEW ACCOUNT INFO
3. MAKE A DEPOSIT
4. MAKE A WITHDRAW
5. CHECK BALANCE
6. CHANGE PERSONAL INFO - TO EDIT MENU OF FIELDS
7. EXIT PROGRAM 

THERE IS ALSO A MENU FOR EMPLOYEE WHICH HAS 3 CAPABILITIES

1. APPROVE ACCOUNTS
2. PULL ALL ACCOUNTS
3. ACCESS CUSTOMER INFORMATION



** APPLICATION ISSUES:
CURRENTLY THERE IS NOT AN ADMIN ROLE

ACCOUNT APPROVAL IS NOT WORKING CORRECTLY WHEN DELETING 
TEXT FILE AND THEN RENAMING IT

EMPLOYEE CAN NOT MANIPULATE AN ACCOUNT


